"""Pins **this repository's own adoption** of the retrospection skip rules (issue #130).

`test_reflect_skip_scope.py` pins the two generic layers: the engine defaults, and the template
data loaded from `project-template/`. Neither says anything about what *this* project gets, and
that is where #130 was reopened: the mechanism shipped (#134) and the read-only comparison shipped
(#146), but a plugin upgrade never writes a project's `.claude/memory/reflect-skip.json`. Adoption
is a per-project act, so it needs a per-project regression.

So these tests load the **committed config of this repository** through the real loader and assert
the verdict matrix it produces:

| PR shape | Verdict here | Comes from |
|---|---|---|
| memory-only | skipped | engine default |
| memory + root `.gitignore` | skipped | this repository's `ignore_paths` (the #130 recurrence) |
| memory + a nested `.gitignore` | **reflected** | `ignore_paths` is root-only: see below |
| rule/agent docs (`AGENTS.md`, `CLAUDE.md`) | **reflected** | deliberate: see below |
| rule docs + `[skip reflect]` / `skip-reflect` label | skipped | engine default marker |
| memory + real source code | reflected | correct |
| `.gitignore` alone | reflected | fail-open, no grounds |

The nested-`.gitignore` row is the second deliberate narrowing. Four of this repository's five
tracked ignore files are shipped product (`project-template/.claude/**`, where
`.claude/memory/.gitignore` is the feature of #113 and a `template_check.py` reference file) or
generated by `build.sh` (`plugins/*/…/template-reference/`); only the root `.gitignore` is policy
noise, so a `**/.gitignore` glob would silently drop shipped changes from the verdict.

The rule-document row is the deliberate difference from `project-template`. The template skips
`CLAUDE.md`/`AGENTS.md`; this repository does not adopt that, because an `AGENTS.md` change
redefined the harness's scope here (#105) and `project-template/AGENTS.md` is shipped product. The
marker is the documented path for a rule-promotion PR. If that judgement is ever revisited, this
file and `docs/self-improvement-hooks.md` are the two places to change — the point is that the
choice cannot drift silently.

Every case runs against **all three copies of the engine** (core and both built adapters), because
the config is read by whichever copy the installed plugin happens to be, and a stale adapter would
otherwise go unnoticed here.
"""
import importlib.util
import pathlib
import tempfile
import unittest
from unittest.mock import patch


ROOT = pathlib.Path(__file__).resolve().parents[1]
REPO_CONFIG = ROOT / ".claude" / "memory" / "reflect-skip.json"
NESTED_TEMPLATE_IGNORE = "project-template/.claude/memory/.gitignore"
TEMPLATE_CLAUDE_IGNORE = "project-template/.claude/.gitignore"
GENERATED_REFERENCE_IGNORES = [
    "plugins/harness/bin/template-reference/.gitignore",
    "plugins/codex/skills/template-check/scripts/template-reference/.gitignore",
]
HOOK_COPIES = {
    "core": ROOT / "core" / "hooks" / "pr-merge-reflect.py",
    "claude_adapter": ROOT / "plugins" / "harness" / "hooks" / "pr-merge-reflect.py",
    "codex_adapter": ROOT / "plugins" / "codex" / "hooks" / "pr-merge-reflect.py",
}


def _load(name, path):
    spec = importlib.util.spec_from_file_location(f"pr_merge_reflect__{name}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ENGINES = {name: _load(name, path) for name, path in HOOK_COPIES.items()}


class _Matrix(unittest.TestCase):
    """Runs one verdict through every engine copy. Only the `gh` lookup is faked.

    The verdict logic is never restated here — `test_reflect_skip_scope.py` records why (a copied
    verdict passed while the production filter was deleted).
    """

    def assertVerdict(self, expected, project_dir, files, labels=(), commits=(), msg=""):
        details = {
            "files": list(files),
            "labels": list(labels),
            "commit_messages": list(commits),
        }
        for name, engine in ENGINES.items():
            with self.subTest(engine=name):
                with patch.object(engine, "_pr_details", return_value=details):
                    got = engine._should_skip_reflect(str(project_dir), 1)
                self.assertEqual(expected, got, msg)


class AdoptionChangesTheVerdictTest(_Matrix):
    """The discriminating pair: the same PR, one project with the config and one without.

    Without this pair "adopted" and "not adopted" are indistinguishable, which is exactly the
    confusion that reopened #130 — the plugin update was read as adoption.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        # A project that participates in the hooks (it has .claude/memory) but never copied
        # reflect-skip.json — the state of every project that adopted the template early.
        self.unadopted = pathlib.Path(self._tmp.name)
        (self.unadopted / ".claude" / "memory").mkdir(parents=True)
        self.addCleanup(self._tmp.cleanup)

    def test_memory_plus_gitignore_needs_the_project_config(self):
        files = [".claude/memory/lesson.md", ".claude/memory/INDEX.md", ".gitignore"]
        self.assertVerdict(
            False, self.unadopted, files,
            msg="an unadopted project must still reflect — the engine does not decide that "
                "a .gitignore change is incidental")
        self.assertVerdict(
            True, ROOT, files,
            msg="this repository's reflect-skip.json is missing or no longer treats .gitignore "
                "as incidental — the #130 recurrence (study-words #422) is back")

    def test_memory_only_never_needed_adoption(self):
        """The engine default. Stated so the pair above is read as the delta it is."""
        files = [".claude/memory/lesson.md"]
        self.assertVerdict(True, self.unadopted, files)
        self.assertVerdict(True, ROOT, files)


class ThisRepositoryMatrixTest(_Matrix):
    """The remaining rows of the table in this file's docstring, against the committed config."""

    def test_rule_and_agent_docs_are_still_reflected_here(self):
        for files in (["AGENTS.md"],
                      ["CLAUDE.md"],
                      ["project-template/AGENTS.md"],
                      ["AGENTS.md", ".claude/memory/lesson.md"],
                      ["docs/self-improvement-hooks.md"]):
            with self.subTest(files=files):
                self.assertVerdict(
                    False, ROOT, files,
                    msg="this repository deliberately does not skip rule documents (#105 was an "
                        "AGENTS.md change that redefined the harness's scope, and "
                        "project-template/AGENTS.md ships to users). If that judgement changed, "
                        "docs/self-improvement-hooks.md has to change with it")

    def test_a_rule_promotion_pr_can_still_be_marked(self):
        """The documented escape hatch for the row above — and it needs no project config."""
        files = ["AGENTS.md", ".claude/memory/lesson.md"]
        self.assertVerdict(True, ROOT, files, commits=["docs: promote lesson [skip reflect]"])
        self.assertVerdict(True, ROOT, files, labels=["skip-reflect"])

    def test_real_source_code_is_reflected(self):
        """Mixed PRs — the direction where over-skipping loses a retrospective silently."""
        for files in (["core/hooks/pr-merge-reflect.py", ".claude/memory/lesson.md"],
                      ["core/hooks/pr-merge-reflect.py", ".claude/memory/lesson.md", ".gitignore"],
                      ["core/scripts/template_check.py", "tests/test_template_check.py"],
                      ["build.sh", ".gitignore"]):
            with self.subTest(files=files):
                self.assertVerdict(False, ROOT, files)

    def test_incidental_files_alone_are_not_grounds_for_a_skip(self):
        """Removing the incidental file leaves nothing to judge, so the PR is reflected."""
        self.assertVerdict(False, ROOT, [".gitignore"])

    def test_shipped_and_generated_ignore_files_stay_in_the_verdict(self):
        """The other direction of the row above: only the root `.gitignore` is incidental."""
        for files in ([NESTED_TEMPLATE_IGNORE, ".claude/memory/lesson.md"],
                      [TEMPLATE_CLAUDE_IGNORE, ".claude/memory/lesson.md"],
                      [NESTED_TEMPLATE_IGNORE, ".claude/memory/lesson.md", ".gitignore"],
                      GENERATED_REFERENCE_IGNORES + [".claude/memory/INDEX.md", ".gitignore"],
                      [NESTED_TEMPLATE_IGNORE]):
            with self.subTest(files=files):
                self.assertVerdict(
                    False, ROOT, files,
                    msg="a shipped or generated ignore file was treated as incidental — "
                        "`ignore_paths` has been widened past the root .gitignore")

    def test_those_ignore_files_really_exist_here(self):
        """Without this, the rows above could keep passing while asserting about nothing."""
        for rel in [NESTED_TEMPLATE_IGNORE, TEMPLATE_CLAUDE_IGNORE] + GENERATED_REFERENCE_IGNORES:
            with self.subTest(path=rel):
                self.assertTrue((ROOT / rel).is_file(), f"{rel} no longer exists — update this "
                                                        f"file's paths rather than deleting the case")

    def test_harness_output_paths_survive_adoption(self):
        """The config extends the defaults rather than replacing them (no `defaults: false`)."""
        for files in ([".claude/handoff/main.md"], [".agents/skills/fw/SKILL.md"]):
            with self.subTest(files=files):
                self.assertVerdict(True, ROOT, files)


class CommittedConfigTest(unittest.TestCase):
    """What the file itself must look like, read through the production loader."""

    def cfg(self, engine):
        return engine._load_reflect_skip_config(str(ROOT))

    def test_the_config_file_exists(self):
        self.assertTrue(REPO_CONFIG.is_file(),
                        f"{REPO_CONFIG.relative_to(ROOT)} is the adoption; without it this "
                        f"repository is in the state #130 was reopened about")

    def test_every_engine_copy_loads_it_identically(self):
        cfgs = {name: self.cfg(engine) for name, engine in ENGINES.items()}
        reference = cfgs["core"]
        for name, cfg in cfgs.items():
            with self.subTest(engine=name):
                self.assertEqual(reference, cfg,
                                 "an adapter copy reads this project's config differently from "
                                 "core — run ./build.sh")
        self.assertIn(".gitignore", reference["ignore_paths"])
        self.assertIn(".claude/memory/**", reference["paths"])

    def test_the_template_list_is_not_adopted_wholesale(self):
        """Guards the judgement in this file's docstring against a silent template copy.

        Copying `project-template/.claude/memory/reflect-skip.json` verbatim into this repository
        would stop retrospectives on rule and shipped-template changes. That may one day be the
        right call, but it is a decision, not a copy — this test makes it one.
        """
        cfg = self.cfg(ENGINES["core"])
        for pattern in ("AGENTS.md", "CLAUDE.md", "**/AGENTS.md", "**/CLAUDE.md"):
            with self.subTest(pattern=pattern):
                self.assertNotIn(pattern, cfg["paths"])


if __name__ == "__main__":
    unittest.main()
